<a href="https://colab.research.google.com/github/ElikemHills/ElikemHills/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr= [6,7,8,9,10]

In [ ]:
print(arr)

[6, 7, 8, 9, 10]


In [ ]:
a= np.array(arr)

In [ ]:
import pandas

In [ ]:
print(a)

[ 6  7  8  9 10]


In [ ]:
a.shape


(5,)

In [ ]:
b=np.array([[1,2,3,4],[5,6,7,8]])

In [ ]:
print(b
  )

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
a.dtype


dtype('int64')

In [ ]:
b.shape

(2, 4)

In [ ]:
b[1][2]

7

In [ ]:
import numpy as np

In [ ]:
b=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

NameError: ignored

In [ ]:
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
b[1]

array([ 7,  8,  9, 10, 11, 12])

In [ ]:
b[0,4]

5

In [ ]:
b[0:0]

array([], shape=(0, 6), dtype=int64)

In [ ]:
b.reshape(2, 2, 3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
b*2

array([[ 2,  4,  6,  8, 10, 12],
       [14, 16, 18, 20, 22, 24]])

In [ ]:
np.random.normal(loc=3, scale=3, size=9)

array([ 2.28431021,  4.30103627, -0.15099026,  0.63295497,  3.68036408,
        0.46650899,  3.69313081,  2.43487122,  7.14106821])

In [ ]:
import math as ma

In [ ]:
2+3

5

In [ ]:
import tensorflow as TF

In [ ]:
replace.tensorflow with {}

SyntaxError: ignored

In [ ]:
print(name[4])

Emmanue


In [ ]:
# @title Default title text
name=['zara','charity','korkoe',['edinam','gifty','faithful','Edwin'],'Emmanue','Bosses']

In [ ]:
print(name)

['zara', 'charity', 'korkoe', ['edinam', 'gifty', 'faithful', 'Edwin'], 'Emmanue', 'Bosses']


In [ ]:
list2=name[3]

In [ ]:
print(list2[0:3][0:2])

['edinam', 'gifty']


In [ ]:
prices=[2,5,7,6,3,1,8,5]

In [ ]:
prices.sort()

In [ ]:
print(prices)

[1, 2, 3, 5, 5, 6, 7, 8]


In [ ]:
Games=[2,3,4.5,'sort',True,6,7]

In [ ]:
print(type(Games))

<class 'list'>


In [ ]:
Games.append('Thursday')

In [ ]:
print(Games)

[2, 3, 4.5, 'sort', True, 6, 7, 'Thursday']


In [ ]:
print({} .format(max(Games)))

AttributeError: ignored

In [ ]:
Games.replace('Thursday','24')

AttributeError: ignored